## https://hexo.io/docs/configuration.html

# Site
title: 艾克斯の编码者
subtitle: 一个伪宅级别的码畜。
description:
author: 死月·吃圡蕾特
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://xcoder.in/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writting
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY年MM月DD日
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: x'new

marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

mathjax: true

feed:
  type: atom
  path: atom.xml
  limit: 0
