title: 艾克斯の編碼者
subtitle: 一個偽宅级别的蒟蒻碼畜。
description: 
author: 小鳥遊死月
email: admin@xcoder.in
language: zh-CN

feed: atom
path: atom.xml
limit: 20

url: http://xcoder.in/
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

source_dir: source
public_dir: public

new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false
external_link: true
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: true
highlight:
  enable: true
  line_number: true
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

server:
  port: 4000
  ip: 0.0.0.0
  log: false

date_format: YYYY年MM月DD日
time_format: H:mm:ss

per_page: 10
pagination_dir: page

theme: hexadillax 
exclude_generator:

markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

stylus:
  compress: false
